name: HackSlash
description: HackSlash - JECRC

license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

favicon: png

exclude: ['README.md', 'LICENSE', 'Gemfile.lock', 'Gemfile', 'vendor']

encoding: "utf-8"
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

email: hackslashjecrc@gmail.com
facebook: HackSlashJECRC
twitter: HackSlashJECRC
github: HackSlashJECRC
medium: HackSlash
instagram: HackSlashJECRC
meetup: HackSlashJECRC
youtube: HackSlashJECRC
